//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlcClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlcClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 注意：
        ///AI/AQ/R区地址单位是word不支持byte/bit读取
        ///
        ///批量读取，一行一个地址
        ///参考示例如下：
        ///I101
        ///Q201
        ///M301
        ///R401
        ///AI501
        ///AQ601
        /// 的本地化字符串。
        /// </summary>
        internal static string getip {
            get {
                return ResourceManager.GetString("getip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明：
        /// 1、关于PLC地址 DB1.DBX2.1、DB2.DBB4、DB3.DBW6、DB4.DBD8中的X、B、W、D分别表示BIT、BYTE、WORD、DWORD数据类型
        /// 2、关于PLC地址：VB100、VW200、VD300中的 V区 相当于DB1区
        ///
        /// PLC数据类型对应C#数据类型关系如下： 
        /// |------------------------------|
        /// | Bit		| Boolean	|
        /// |------------------------------|
        /// | Byte		| Byte		|
        /// |------------------------------|
        /// | DInt		| Int32(Int)	|
        /// |------------------------------|
        /// | Real		| Single(Float)	|
        /// |------------------------------|
        /// | LReal	| Double	|
        /// |------------------------------|
        /// | Word		| UInt16(UShort)|        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string tip {
            get {
                return ResourceManager.GetString("tip", resourceCulture);
            }
        }
    }
}
